"""schema initial

Revision ID: 3e84938196d2
Revises: 
Create Date: 2026-08-04 14:13:00.600094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e84938196d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('resume_raw', sa.Text(), nullable=True),
    sa.Column('resume_file', sa.LargeBinary(), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('resume_mime', sa.String(length=100), nullable=True),
    sa.Column('cv_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"summary": str, "experiences": [...], "education": [...], "languages": [...]}'),
    sa.Column('signature_image', sa.Text(), nullable=True),
    sa.Column('cv_design', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='{"mode": "original"|"template", "template_id": str, "color_hex": str, "show_photo": bool}'),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.String()), nullable=False, comment="Cities/regions of interest, e.g. ['Paris', 'Lyon']"),
    sa.Column('preferred_remote_policies', postgresql.ARRAY(sa.String()), nullable=False, comment="e.g. ['remote', 'hybrid']"),
    sa.Column('preferred_contract_types', postgresql.ARRAY(sa.String()), nullable=False, comment="e.g. ['cdi', 'freelance']"),
    sa.Column('matching_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='MatchingCriteria: filtres durs (langue, pays, métier, exclusions) et pondérations. Null = dérivé du profil à la volée.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('siren', sa.String(length=9), nullable=True),
    sa.Column('careers_url', sa.Text(), nullable=True),
    sa.Column('ats_type', sa.Enum('GREENHOUSE', 'LEVER', 'WORKDAY', 'WORKABLE', 'ASHBY', 'SMARTRECRUITERS', 'CUSTOM', 'UNKNOWN', name='atstype'), nullable=False),
    sa.Column('ats_slug', sa.String(length=255), nullable=True, comment='board_token (Greenhouse) or company_slug (Lever)'),
    sa.Column('status', sa.Enum('PENDING', 'ATS_DIRECT', 'FORM_STANDARD', 'COMPLEX_WORKDAY', 'NO_CAREER_PAGE', 'ERROR', name='companystatus'), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('naf_code', sa.String(length=10), nullable=True),
    sa.Column('size_category', sa.String(length=50), nullable=True, comment='startup / pme / eti / grand_groupe'),
    sa.Column('location_hq', sa.String(length=255), nullable=True),
    sa.Column('seed_source', sa.Enum('WTTJ_SITEMAP', 'ECOSYSTEM_FT120', 'ECOSYSTEM_NEXT40', 'ECOSYSTEM_VC', 'SIRENE_API', 'ATS_INDEX', 'MANUAL', name='seedsource'), nullable=False),
    sa.Column('scrape_frequency_hours', sa.Integer(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolve_error', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_status'), 'companies', ['status'], unique=False)
    op.create_table('job_postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False, comment='ID in the source ATS (Greenhouse job ID, Lever posting ID, etc.)'),
    sa.Column('fingerprint', sa.String(length=64), nullable=False, comment='SHA-256 hash for deduplication'),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('description_parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured extraction by LLM (Sprint 2)'),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('remote_policy', sa.Enum('REMOTE', 'HYBRID', 'ONSITE', 'UNKNOWN', name='remotepolicy'), nullable=False),
    sa.Column('contract_type', sa.Enum('CDI', 'CDD', 'FREELANCE', 'STAGE', 'ALTERNANCE', 'INTERIM', 'UNKNOWN', name='contracttype'), nullable=False),
    sa.Column('experience_range', sa.String(length=50), nullable=True),
    sa.Column('salary_range', sa.String(length=100), nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=True),
    sa.Column('apply_channel', sa.Enum('GREENHOUSE_API', 'LEVER_API', 'WORKABLE_API', 'ASHBY_API', 'WEB_FORM', 'EMAIL', 'EXTERNAL_LINK', 'UNKNOWN', name='applychannel'), nullable=False),
    sa.Column('apply_complexity', sa.Enum('SIMPLE', 'MEDIUM', 'COMPLEX', name='applycomplexity'), nullable=False),
    sa.Column('contact_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'EXPIRED', name='postingstatus'), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True, comment='0-100 matching score vs candidate profile'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_company_id'), 'job_postings', ['company_id'], unique=False)
    op.create_index(op.f('ix_job_postings_fingerprint'), 'job_postings', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False, comment='Une seule mission par candidat.'),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='missionstatus'), nullable=False),
    sa.Column('autonomy', sa.Enum('PROPOSE', 'AUTO_ABOVE', 'FULL', name='autonomylevel'), nullable=False),
    sa.Column('auto_apply_min_score', sa.Integer(), nullable=False, comment='Score à partir duquel AUTO_ABOVE envoie sans demander.'),
    sa.Column('weekly_quota', sa.Integer(), nullable=False, comment='Nombre maximum de candidatures par semaine.'),
    sa.Column('allowed_channels', postgresql.ARRAY(sa.String()), nullable=True, comment='email | web_form | ats_api'),
    sa.Column('blocked_companies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_candidate_id'), 'missions', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_posting_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'MATCHED', 'APPLIED', 'REJECTED', 'INTERVIEW', 'OFFER', 'CLOSED', name='applicationstatus'), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Tracks apply history, step guidance, resume adapted versions, etc.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_posting_id', name='uq_candidate_job')
    )
    op.create_index(op.f('ix_applications_candidate_id'), 'applications', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_applications_job_posting_id'), 'applications', ['job_posting_id'], unique=False)
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('mission_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('objective', sa.String(length=64), nullable=False, comment="search | prepare | apply — jusqu'où va la pipeline."),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PREPARING', 'RUNNING', 'COMPLETED', 'INTERRUPTED', name='runstatus'), nullable=False),
    sa.Column('current_step', sa.Enum('SCAN', 'QUALIFY', 'MATCH', 'PREPARE', 'APPLY', name='runstep'), nullable=True),
    sa.Column('allowed_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_runs_mission_id'), 'mission_runs', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_runs_status'), 'mission_runs', ['status'], unique=False)
    op.create_table('application_dispatches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True, comment="Mission qui a produit cette candidature, si elle vient d'un run."),
    sa.Column('job_title', sa.String(length=500), nullable=False),
    sa.Column('company_name', sa.String(length=300), nullable=False),
    sa.Column('channel', sa.Enum('EMAIL', 'WEB_FORM', 'ATS_API', 'MANUAL', name='dispatchchannel'), nullable=False),
    sa.Column('destination', sa.Text(), nullable=True, comment='Adresse email ou URL du formulaire.'),
    sa.Column('documents', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resume_blob', sa.LargeBinary(), nullable=True),
    sa.Column('resume_name', sa.String(length=255), nullable=True),
    sa.Column('letter_subject', sa.String(length=500), nullable=True),
    sa.Column('letter_body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PREPARED', 'AWAITING_APPROVAL', 'APPROVED', 'SENT', 'FAILED', 'REJECTED', 'SIMULATED', name='dispatchstatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('proof', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Preuve d'envoi : id de message SMTP, capture, réponse HTTP."),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['mission_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_dispatches_application_id'), 'application_dispatches', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_dispatches_candidate_id'), 'application_dispatches', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_application_dispatches_created_at'), 'application_dispatches', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_dispatches_run_id'), 'application_dispatches', ['run_id'], unique=False)
    op.create_index(op.f('ix_application_dispatches_status'), 'application_dispatches', ['status'], unique=False)
    op.create_index('uq_dispatch_sent_once', 'application_dispatches', ['application_id'], unique=True, postgresql_where=sa.text("status = 'SENT'"))
    op.create_table('mission_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Enum('MISSION_CREATED', 'MANDATE_CHANGED', 'AUTONOMY_CHANGED', 'STATUS_CHANGED', 'SCAN', 'SHORTLIST', 'DISCARD', 'CV_ADAPTED', 'LETTER_WRITTEN', 'APPLIED', 'AWAITING_APPROVAL', 'REPLY', 'ERROR', name='missioneventkind'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False, comment="Phrase lisible telle qu'Alice la raconterait."),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Détail structuré : ids d'offres, motifs de rejet, compteurs."),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['mission_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_events_created_at'), 'mission_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_mission_events_kind'), 'mission_events', ['kind'], unique=False)
    op.create_index(op.f('ix_mission_events_mission_id'), 'mission_events', ['mission_id'], unique=False)
    op.create_index(op.f('ix_mission_events_run_id'), 'mission_events', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mission_events_run_id'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_mission_id'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_kind'), table_name='mission_events')
    op.drop_index(op.f('ix_mission_events_created_at'), table_name='mission_events')
    op.drop_table('mission_events')
    op.drop_index('uq_dispatch_sent_once', table_name='application_dispatches', postgresql_where=sa.text("status = 'SENT'"))
    op.drop_index(op.f('ix_application_dispatches_status'), table_name='application_dispatches')
    op.drop_index(op.f('ix_application_dispatches_run_id'), table_name='application_dispatches')
    op.drop_index(op.f('ix_application_dispatches_created_at'), table_name='application_dispatches')
    op.drop_index(op.f('ix_application_dispatches_candidate_id'), table_name='application_dispatches')
    op.drop_index(op.f('ix_application_dispatches_application_id'), table_name='application_dispatches')
    op.drop_table('application_dispatches')
    op.drop_index(op.f('ix_mission_runs_status'), table_name='mission_runs')
    op.drop_index(op.f('ix_mission_runs_mission_id'), table_name='mission_runs')
    op.drop_table('mission_runs')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_posting_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_candidate_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_fingerprint'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company_id'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_companies_status'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
