"""password hash for candidates

Revision ID: 50980516fd4c
Revises: 730c3462ab02
Create Date: 2026-08-10 23:18:07.428597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50980516fd4c'
down_revision: Union[str, Sequence[str], None] = '730c3462ab02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('password_hash', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'password_hash')
    # ### end Alembic commands ###
