"""smtp candidat

Revision ID: 567d62ab7d94
Revises: 3c82c3453a6d
Create Date: 2026-08-11 00:18:33.205404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567d62ab7d94'
down_revision: Union[str, Sequence[str], None] = '3c82c3453a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('smtp_email', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('smtp_app_password_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'smtp_app_password_encrypted')
    op.drop_column('candidates', 'smtp_email')
    # ### end Alembic commands ###
