"""recruiter messages

Revision ID: 730c3462ab02
Revises: c3eae8fff71a
Create Date: 2026-08-10 18:53:20.715383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730c3462ab02'
down_revision: Union[str, Sequence[str], None] = 'c3eae8fff71a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiter_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('dispatch_id', sa.UUID(), nullable=True, comment="Candidature d'origine, quand la réponse a pu y être rattachée."),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='messagedirection'), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=300), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dispatch_id'], ['application_dispatches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiter_messages_candidate_id'), 'recruiter_messages', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_recruiter_messages_dispatch_id'), 'recruiter_messages', ['dispatch_id'], unique=False)
    op.create_index(op.f('ix_recruiter_messages_is_read'), 'recruiter_messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_recruiter_messages_received_at'), 'recruiter_messages', ['received_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiter_messages_received_at'), table_name='recruiter_messages')
    op.drop_index(op.f('ix_recruiter_messages_is_read'), table_name='recruiter_messages')
    op.drop_index(op.f('ix_recruiter_messages_dispatch_id'), table_name='recruiter_messages')
    op.drop_index(op.f('ix_recruiter_messages_candidate_id'), table_name='recruiter_messages')
    op.drop_table('recruiter_messages')
    # ### end Alembic commands ###
