"""battement de coeur des runs de mission

Revision ID: c3eae8fff71a
Revises: 3e84938196d2
Create Date: 2026-08-04 14:38:54.397872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3eae8fff71a'
down_revision: Union[str, Sequence[str], None] = '3e84938196d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('candidates', 'cv_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{"summary": str, "experiences": [...], "education": [...], "languages": [...]}',
               existing_nullable=True)
    op.alter_column('candidates', 'cv_design',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='{"mode": "original"|"template", "template_id": str, "color_hex": str, "show_photo": bool}',
               existing_nullable=True)
    op.alter_column('candidates', 'matching_criteria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='MatchingCriteria: filtres durs (langue, pays, métier, exclusions) et pondérations. Null = dérivé du profil à la volée.',
               existing_nullable=True)
    op.add_column('mission_runs', sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True, comment="Dernier signe de vie du worker. Un processus tué net ne peut pas clore son run : c'est l'absence de battement, et non le statut en base, qui permet de savoir qu'une mission n'existe plus."))
    op.alter_column('missions', 'allowed_channels',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment='email | web_form | ats_api',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'allowed_channels',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               comment=None,
               existing_comment='email | web_form | ats_api',
               existing_nullable=True)
    op.drop_column('mission_runs', 'heartbeat_at')
    op.alter_column('candidates', 'matching_criteria',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='MatchingCriteria: filtres durs (langue, pays, métier, exclusions) et pondérations. Null = dérivé du profil à la volée.',
               existing_nullable=True)
    op.alter_column('candidates', 'cv_design',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"mode": "original"|"template", "template_id": str, "color_hex": str, "show_photo": bool}',
               existing_nullable=True)
    op.alter_column('candidates', 'cv_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='{"summary": str, "experiences": [...], "education": [...], "languages": [...]}',
               existing_nullable=True)
    # ### end Alembic commands ###
